# Stubs for easyjwt.easyjwt (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from . import Algorithm
from .restoration import restore_timestamp_to_datetime
from datetime import datetime
from typing import ClassVar, Iterable, Optional, Set, Type, TypeVar, Union

EasyJWTClass = TypeVar('EasyJWTClass', bound='EasyJWT')

class EasyJWT:
    algorithm: ClassVar[Algorithm] = ...
    previous_algorithms: ClassVar[Set[Algorithm]] = ...
    strict_verification: ClassVar[bool] = ...
    audience: Optional[Union[Iterable[str], str]]
    expiration_date: Optional[datetime]
    issued_at_date: Optional[datetime]
    issuer: Optional[str]
    JWT_ID: Optional[str]
    not_before_date: Optional[datetime]
    subject: Optional[str]
    def __init__(self, key: str) -> None: ...
    def create(self, issued_at: Optional[datetime]=...) -> str: ...
    @classmethod
    def verify(cls: Type[EasyJWTClass], token: str, key: str, issuer: Optional[str]=..., audience: Optional[Union[Iterable[str], str]]=...) -> EasyJWTClass: ...
