# Stubs for easyjwt.enums (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from enum import Enum

class Algorithm(Enum):
    HS256: str = ...
    HS384: str = ...
    HS512: str = ...
