# Stubs for easyjwt.errors (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Iterable, Optional, Set

class EasyJWTError(Exception):
    def __init__(self, message: str) -> None: ...

class IncompatibleKeyError(EasyJWTError): ...
class CreationError(EasyJWTError): ...

class MissingRequiredClaimsError(CreationError):
    missing_claims: Set[str]
    def __init__(self, missing_claims: Iterable[str]) -> None: ...

class VerificationError(EasyJWTError): ...

class ExpiredTokenError(VerificationError):
    def __init__(self) -> None: ...

class ImmatureTokenError(VerificationError):
    def __init__(self) -> None: ...

class InvalidAudienceError(VerificationError):
    def __init__(self) -> None: ...

class InvalidClaimSetError(VerificationError):
    missing_claims: Set[str]
    unexpected_claims: Set[str]
    def __init__(self, missing_claims: Optional[Iterable[str]]=..., unexpected_claims: Optional[Iterable[str]]=...) -> None: ...

class InvalidClassError(VerificationError):
    actual_class: str
    expected_class: str
    def __init__(self, expected_class: str, actual_class: str) -> None: ...

class InvalidIssuedAtError(VerificationError):
    def __init__(self) -> None: ...

class InvalidIssuerError(VerificationError):
    def __init__(self) -> None: ...

class InvalidSignatureError(VerificationError):
    def __init__(self) -> None: ...

class UnspecifiedClassError(VerificationError):
    def __init__(self) -> None: ...

class UnsupportedAlgorithmError(VerificationError):
    def __init__(self) -> None: ...
