# Stubs for easyjwt.restoration (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from datetime import datetime
from typing import Optional

def restore_timestamp_to_datetime(timestamp: Optional[int]) -> Optional[datetime]: ...
